name: 反馈问题 🐛
description: 项目运行中遇到的Bug或问题。
title: "🐞 反馈问题："
labels: ['status: needs check']
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ 前置确认 (温馨提示: 未star项目会被自动关闭issue哦!)
        1. 你的环境是否与本文档中的建议一致？
        2. 是否完全按照本文档进行部署？
        3. 单台服务器最低规格是否 > 4C8G？
        4. Linux 内核的版本必须是否是 3.10 以上？
        5. 机器的 hostname 是否标准？
        6. 所有节点服务器时钟是否同步？
  - type: checkboxes
    attributes:
      label: 前置确认
      options:
        - label: 我确认我的环境与本文档中的建议一致，上面的前置条件均满足要求.
          required: true
  - type: checkboxes
    attributes:
      label: ⚠️ 搜索issues中是否已存在类似问题
      description: >
        请在 [历史issue](https://github.com/dqzboy/Deploy_K8sCluster/issues) 中清空输入框，搜索你的问题
        或相关日志的关键词来查找是否存在类似问题。
      options:
        - label: 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue
          required: true
  - type: markdown
    attributes:
      value: |
        请在上方的`title`中填写你对你所遇到问题的简略总结，这将帮助其他人更好的找到相似问题，谢谢❤️。
  - type: dropdown
    attributes:
      label: 操作系统类型?
      description: >
        请选择你运行程序的操作系统类型。
      options:
        - CentOS 7
        - CentOS 8
        - Redhat
        - Ubuntu
        - Other (请在问题中说明)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤 🕹
      description: |
        **⚠️ 不能复现将会关闭issue.**
  - type: textarea
    attributes:
      label: 问题描述 😯
      description: 详细描述出现的问题，或提供有关截图。
  - type: textarea
    attributes:
      label: 终端日志 📒
      description: |
        在此处粘贴终端日志
      value: |
        ```log
        <此处粘贴终端日志>
        ```
